version: "3.8"

services:
  bot:
    build: .
    container_name: tehnikapremiumcatalogbot
    env_file:
      - .env
    restart: always
    volumes:
      - ${PWD}/files:/app/files
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - $PGPORT:$PGPORT
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
